# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By


class TestLKPATOLID():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_lKPATOLID(self):
        #  self.driver.get("https://lkp.atol.ru/catalog")
        self.driver.get(
            "https://id.atol.ru/auth/realms/ATOL-ID-External/protocol/openid-connect/auth?client_id=lkp_client&redirect_uri=https%3A%2F%2Flkp.atol.ru%2Fcatalog&state=8b8f1850-d597-43a9-8339-da5112dea2f4&response_mode=fragment&response_type=code&scope=openid&nonce=8adb72d6-d3bb-4453-ad53-86dec857a88a")
        self.driver.set_window_size(1420, 804)
        self.driver.find_element(By.CSS_SELECTOR, ".phoneNumber .atol-Input_value").click()
        self.driver.find_element(By.CSS_SELECTOR, ".phoneNumber .atol-Input_value").send_keys("9251946392")
        self.driver.find_element(By.ID, "password").send_keys("Gfhjkmyjdsq987@")
        self.driver.find_element(By.ID, "kc-login").click()
        element = self.driver.find_element(By.CSS_SELECTOR, ".v-btn:nth-child(2) svg")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".v-btn:nth-child(2) svg").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "body")
        actions = ActionChains(self.driver)
        actions.move_to_element(element, 0, 0).perform()
        self.driver.find_element(By.CSS_SELECTOR, ".v-btn:nth-child(1) svg").click()

    def test_ACID(self):
        pass
